apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "tenzu-back.fullname" . }}-caddy-config"
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
data:
  Caddyfile: |
    :80 {
      request_body {
        max_size 1gb
      }

      encode gzip
      header X-Forwarded-Proto https
      route /live/ {
              respond 200
      }
      route /ready/ {
              respond 200
      }
      @public {
        path /static/* /media/*
      }
      route @public {
              header Access-Control-Allow-Origin *
              header Access-Control-Allow-Headers *
              header Access-Control-Allow-Methods *
              header Cache-Control 3600
# TODO don't hardcode this path
              root * /code/public/
              encode gzip
              file_server {
                  precompressed br gzip
              }
      }
      reverse_proxy http://{{ include "tenzu-back.fullname" . }}:{{ .Values.service.port }} {
          header_up X-Forwarded-Proto https
          transport http {
                response_header_timeout {{.Values.workersTimeout}}s
            }
      }
    }
