apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "tenzu-back.fullname" . }}-caddy-config"
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-1"
data:
  Caddyfile: |
    :80 {
      request_body {
        max_size 1gb
      }

      encode gzip
      header X-Forwarded-Proto https
      route /live/ {
              respond 200
      }
      route /ready/ {
              respond 200
      }
      reverse_proxy http://localhost:{{ .Values.service.port }} {
          header_up X-Forwarded-Proto https
          transport http {
                response_header_timeout {{.Values.workersTimeout}}s
            }
      }
    }
