apiVersion: v1
kind: Service
metadata:
  name: {{ include "tenzu-back.fullname" . }}-caddy
  labels:
    {{- include "tenzu-back.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    {{- include "tenzu-back.labels" . | nindent 4 }}

