apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "tenzu-front.fullname" . }}-config"
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-1"
data:
  config.json: |
    {
      "env": "{{ .Values.config.environment }}",
      "api": {
        "prefix": "{{ .Values.config.prefix }}",
        "suffixDomain": "{{ .Values.config.suffixDomain }}",
        "baseDomain": "{{ .Values.global.backendUrl.host }}",
        "scheme": "{{ .Values.global.backendUrl.scheme }}"
      },
{{- if .Values.sentry.enabled }}
      "sentry": {
        "dsn": "{{ .Values.sentry.dsn }}",
        "environment": "{{ .Values.sentry.environment | default .Values.config.environment }}"
      },
{{- end }}
      "wsUrl": "{{ .Values.global.backendUrl.websocketScheme }}://{{ .Values.global.backendUrl.host }}/events/"
    }