apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "tenzu-front.fullname" . }}-config"
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
data:
  config.json: |
    {
      "api": {
        "baseDomain": "{{ .Values.global.tenzu.backendUrl.host }}",
        "scheme": "{{ .Values.tenzu.backendUrl.scheme }}"
      },
{{- if .Values.sentry.enabled }}
      "sentry": {
        "dsn": "{{ .Values.sentry.dsn }}"
        "environment": "{{ .Values.sentry.environment | default "production" }}"
      },
{{- end }}
      "wsUrl": "{{ .Values.tenzu.backendUrl.websocketScheme }}://{{ .Values.global.tenzu.backendUrl.host }}/events/"
    }