# Default values for django-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: 

# change liveness and readiness
livenessProbe:
  httpGet:
    path: /health_check/
    port: 8000
    httpHeaders:
      - name: Host
        value: chart-example.local
readinessProbe:
  httpGet:
    path: /health_check/
    port: 8000
    httpHeaders:
      - name: Host
        value: chart-example.local