# Default values for tenzu.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

postgresql:
  # -- Whether to enable bitnami provided postgresql chart as a dependency
  # If you do, fill the postgresql parameters in global key so it can also be used by tenzu-back
  enabled: true

redis:
  # -- Whether to enable bitnami provided redis chart as a dependency
  # If you do, fill the redis parameters in global key so it can also be used by tenzu-back
  enabled: true
