apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "django-app.fullname" . }}-caddy"
  labels:
    {{- include "django-app.caddyLabels" . | nindent 4 }}
spec:
  replicas: {{.Values.caddy.replicas}}
  selector:
    matchLabels:
      {{- include "django-app.caddyLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "django-app.caddyLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-caddy
          image: caddy:2.4.5-alpine
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /live/
              port: 80
          readinessProbe:
            httpGet:
              path: /ready/
              port: 80
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: public
              mountPath: /code/public/
            - mountPath: /etc/caddy/Caddyfile
              name: config
              subPath: Caddyfile
      volumes:
        - name: public
          persistentVolumeClaim:
            claimName: pvc-{{ .Release.Name }}
        - name: config
          configMap:
            name: "{{ include "django-app.fullname" . }}-caddy-config"
            items:
              - key: Caddyfile
                path: Caddyfile
                mode: 0644
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-app.fullname" . }}
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "django-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "django-app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "django-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SITE_DOMAIN
              value: {{ first .Values.ingress.hosts }}
            {{- if not (empty .Values.env )}}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: django-secrets
            - configMapRef:
                name: {{ include "django-app.fullname" . }}-configmap
          {{- if not (empty .Values.envFrom )}}
          {{- toYaml .Values.envFrom | nindent 12 }}
          {{- end }}
          command: ["gunicorn"]
          args:
            - "configurations.asgi:application"
            - "-k"
            - "uvicorn.workers.UvicornWorker"
            - "-n"
            - "{{ include "django-app.fullname" . }}"
            - "-w"
            - "{{ .Values.workersQuantity }}"
            - "-t"
            - "{{ .Values.workersTimeout }}"
            - "-b 0.0.0.0:{{ .Values.service.port }}"
            - "--access-logfile"
            - "-"
            - "--log-file"
            - "-"
            - "--capture-output"
            - "--log-level"
            - "{{ .Values.logLevel | default "warning" }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-app.fullname" . }}-worker
  labels:
    {{- include "django-app.workerLabels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "django-app.workerLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "django-app.workerLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "django-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if not (empty .Values.env )}}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: django-secrets
            - configMapRef:
                name: {{ include "django-app.fullname" . }}-configmap
          {{- if not (empty .Values.envFrom )}}
          {{- toYaml .Values.envFrom | nindent 12 }}
          {{- end }}
          command: ["python"]
          args:
            - "manage.py"
            - "procrastinate"
            - "worker"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
