apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "django-app.fullname" . }}-migrate
  labels:
    app.kubernetes.io/component: db
    job-name: "{{ .Release.Name }}-migrate"
    {{- include "django-app.labels" . | nindent 4 }}
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": BeforeHookCreation
spec:
  template:
    metadata:
      name: {{ include "django-app.fullname" . }}
      labels:
        {{- include "django-app.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
      - name: migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["./manage.py", "migrate", "--noinput"]
        env:
          - name: ALLOWED_HOSTS
            value: {{ join "," .Values.ingress.hosts }}
          - name: CSRF_TRUSTED_ORIGINS
            value: "{{range $i, $v := .Values.ingress.hosts }}{{if $i}},{{end}}https://{{.}}{{end}}"
          - name: SITE_DOMAIN
            value: {{ first .Values.ingress.hosts }}
          {{- if not (empty .Values.env )}}
          {{- toYaml .Values.env | nindent 10 }}
          {{- end }}
        envFrom:
          - secretRef:
              name: django-secrets
          - configMapRef:
              name: {{ include "django-app.fullname" . }}-configmap
        {{- if not (empty .Values.envFrom )}}
        {{- toYaml .Values.envFrom | nindent 10 }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "django-app.fullname" . }}-collectstatic
  labels:
    app.kubernetes.io/component: db
    job-name: "{{ .Release.Name }}-collectstatic"
    {{- include "django-app.labels" . | nindent 4 }}
  annotations:
    "argocd.argoproj.io/hook": PreSync
    "argocd.argoproj.io/hook-delete-policy": BeforeHookCreation
spec:
  template:
    metadata:
      name: {{ include "django-app.fullname" . }}
      labels:
        {{- include "django-app.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
      - name: collectstatic
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["./manage.py", "collectstatic", "--noinput"]
        env:
          - name: ALLOWED_HOSTS
            value: {{ join "," .Values.ingress.hosts }}
          - name: CSRF_TRUSTED_ORIGINS
            value: "{{range $i, $v := .Values.ingress.hosts }}{{if $i}},{{end}}https://{{.}}{{end}}"
          - name: SITE_DOMAIN
            value: {{ first .Values.ingress.hosts }}
          {{- if not (empty .Values.env )}}
          {{- toYaml .Values.env | nindent 10 }}
          {{- end }}
        envFrom:
          - secretRef:
              name: django-secrets
          - configMapRef:
              name: {{ include "django-app.fullname" . }}-configmap
        {{- if not (empty .Values.envFrom )}}
        {{- toYaml .Values.envFrom | nindent 10 }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - name: public
            mountPath: /code/public/
      volumes:
        - name: public
          persistentVolumeClaim:
            claimName: pvc-{{ .Release.Name }}
{{- range $job := .Values.cronJobs }}
{{- with $ }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "django-app.fullname" . }}-{{ $job.name }}
  labels:
    job-name: "{{ $.Release.Name }}-{{ $job.name }}"
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  schedule: {{ $job.schedule }}
  jobTemplate:
    metadata:
      name: {{ include "django-app.fullname" . }}
      labels:
        {{- include "django-app.labels" . | nindent 8 }}
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          containers:
          - name: reset
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            command:
              {{- toYaml $job.command | nindent 14 }}
            env:
              - name: ALLOWED_HOSTS
                value: {{ join "," .Values.ingress.hosts }}
              - name: CSRF_TRUSTED_ORIGINS
                value: "{{range $i, $v := .Values.ingress.hosts }}{{if $i}},{{end}}https://{{.}}{{end}}"
              - name: SITE_DOMAIN
                value: {{ first .Values.ingress.hosts }}
              {{- if not (empty .Values.env )}}
              {{- toYaml .Values.env | nindent 14 }}
              {{- end }}
            envFrom:
              - secretRef:
                  name: django-secrets
              - configMapRef:
                  name: {{ include "django-app.fullname" . }}-configmap
            {{- if not (empty .Values.envFrom )}}
            {{- toYaml .Values.envFrom | nindent 14 }}
            {{- end }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
{{ end -}}
{{ end -}}