{{- if not (empty .Values.django_secrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
{{- range $key, $val := .Values.django_secrets }}
  {{ $key }} : {{ $val | quote }}
{{ end -}}
{{ end -}}