postgresql:
  # It's usually the service used for postgres
  host: "tenzu-test-postgresql.tenzu-test.svc.cluster.local"
  # Can be defined here as well but override by the global values and not used by bitnami/postgresql
  # auth:
  #   username: "username"
  #   database: "database"
  #   password: "VerySecurePassword"
redis:
  # It's usually the service used for redis
  host: "tenzu-test-redis-headless.tenzu-test.svc.cluster.local"
  # If you prefer to define the password here but it will not be used bitnami/redis
  # password: "RedisIsAwesomePassword"
# Email configuration
email:
  # The default from email
  defaultFrom: "from@mycompany.com"
  # The host of the email server
  host: "ssl0.ovh.net"
  # The user of the email server
  user: "myUser@mycompany.com"
  # The password of the email server
  password: "verySecurePassword"
  # If the email server uses tls
  tls: True
  # If the email server uses ssl
  ssl: False
# The email for the support
supportEmail: "ask@tenzu.net"


# Define the secret key for Django
secretKey: "qjiqjhnqijqisjosqjdçj#"
# Define the Token SigninKey
tokensSigningKey: "sjisjisjs,silqjdqj"

# Enable ingress configuration
ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    # use cert-manager to generate the certificate
    cert-manager.io/cluster-issuer: letsencrypt-production-dns01
  # The host where will be expose the service
  hosts:
    - tenzu-api-test.domain.org
  tls:
    - hosts:
        - tenzu-api-test.domain.org
      secretName: tenzu-api-test.domain.org-tls

global:
  tenzu:
    # Put the host of the frontend
    frontendDomain: tenzu-test.domain.org
    # Copy the host defined in the ingress earlier
    backendDomain: tenzu-api-test.domain.org
  # Define postgresql credentials in global (will be used by bitnami/postgresql)
  postgresql:
    auth:
      username: "username"
      database: "database"
      password: "VerySecurePassword"
  # Define redis credentials in global (will be used by bitnami/redis)
  redis:
    password: "RedisIsAwesomePassword"