postgresql:
  # It's usually the service used for postgres
  host: "tenzu-test-postgresql.tenzu-test.svc.cluster.local"
  auth:
    # The secret name that contains the credentials for connect to postgres
    existingSecret: "my-postgres-secret"
    # The key in the secret that contains the password
    passwordKey: "pswd"
    # flat values of username and database
    username: "username"
    database: "database"
    # You can load the rest of the values from the secret as well
    # databaseKey: "database"
    # usernameKey: "username"
redis:
  # It's usually the service used for redis
  host: "tenzu-test-redis-headless.tenzu-test.svc.cluster.local"
  # Existing secret that contains the password
  existingSecret: "my-redis-secret"
  # The key that contains the password
  passwordKey: "passwordKey"
# Email configuration
email:
  # The default from email
  defaultFrom: "from@mycompany.com"
  # The host of the email server
  host: "ssl0.ovh.net"
  # The user of the email server
  user: "myUser@mycompany.com"
  # The password of the email server
  password: "verySecurePassword"
  # If the email server uses tls
  tls: True
  # If the email server uses ssl
  ssl: False
# The email for the support
supportEmail: "ask@tenzu.net"

global:
  tenzu:
    # The domain of the frontend
    # If exposed via ingress, it should be the same as the ingress domain
    frontendDomain: tenzu-test.biru.sh
    # The domain of the backend
    # If exposed via ingress, it should be the same as the ingress domain
    backendDomain: tenzu-api-test.biru.sh